sonar.projectKey=MartaPagliuso_BugBoard2026
sonar.organization=martapagliuso

sonar.sources=backend/src
sonar.tests=backend/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
